import { DataSource } from 'typeorm';
import { PromoCode } from '../../database/entities/promo-code.entity';
import {
  PromoCodeType,
  PromoCodeStatus,
  PromoCodeApplicability,
} from '../../common/enums/misc.enum';

export async function seedPromoCodes(dataSource: DataSource): Promise<void> {
  const promoRepository = dataSource.getRepository(PromoCode);

  console.log('🔧 Seeding promo codes...');

  const promoCodes = [
    {
      code: 'WELCOME2025',
      type: PromoCodeType.PERCENTAGE,
      status: PromoCodeStatus.ACTIVE,
      applicability: PromoCodeApplicability.ALL_USERS,
      description: 'Welcome discount for all new customers',
      descriptionAr: 'خصم الترحيب لجميع العملاء الجدد',
      discountPercentage: 20,
      maxDiscountAmount: 100.00,
      minOrderAmount: 150.00,
      maxUsesPerUser: 1,
      currentUses: 45,
      validFrom: new Date('2025-01-01T00:00:00Z'),
      validUntil: new Date('2025-12-31T23:59:59Z'),
      isFirstBookingOnly: true,
      isPublic: true,
      isFeatured: true,
      campaignName: 'New Year Welcome Campaign',
      isActive: true,
      usageCount: 45,
      maxUsage: 500,
      maxUsagePerUser: 1,
      discountType: 'PERCENTAGE',
      discountValue: 20,
    },
    {
      code: 'CLEAN50',
      type: PromoCodeType.FIXED_AMOUNT,
      status: PromoCodeStatus.ACTIVE,
      applicability: PromoCodeApplicability.SPECIFIC_CATEGORIES,
      description: '50 SAR off on cleaning services',
      descriptionAr: 'خصم 50 ريال على خدمات التنظيف',
      discountAmount: 50.00,
      minOrderAmount: 200.00,
      maxUsesPerUser: 3,
      currentUses: 128,
      validFrom: new Date('2025-01-15T00:00:00Z'),
      validUntil: new Date('2025-03-31T23:59:59Z'),
      applicableServiceCategories: ['cleaning'],
      isFirstBookingOnly: false,
      isPublic: true,
      isFeatured: true,
      campaignName: 'Cleaning Services Promotion',
      isActive: true,
      usageCount: 128,
      maxUsage: 1000,
      maxUsagePerUser: 3,
      discountType: 'FIXED_AMOUNT',
      discountValue: 50,
    },
    {
      code: 'RAMADAN30',
      type: PromoCodeType.PERCENTAGE,
      status: PromoCodeStatus.SCHEDULED,
      applicability: PromoCodeApplicability.ALL_USERS,
      description: 'Special Ramadan discount',
      descriptionAr: 'خصم رمضان الخاص',
      discountPercentage: 30,
      maxDiscountAmount: 150.00,
      minOrderAmount: 300.00,
      maxUsesPerUser: 5,
      currentUses: 0,
      validFrom: new Date('2025-02-28T00:00:00Z'),
      validUntil: new Date('2025-03-30T23:59:59Z'),
      isFirstBookingOnly: false,
      isPublic: true,
      isFeatured: true,
      campaignName: 'Ramadan Special',
      isActive: true,
      usageCount: 0,
      maxUsage: 2000,
      maxUsagePerUser: 5,
      discountType: 'PERCENTAGE',
      discountValue: 30,
    },
    {
      code: 'VIPGOLD',
      type: PromoCodeType.PERCENTAGE,
      status: PromoCodeStatus.ACTIVE,
      applicability: PromoCodeApplicability.SPECIFIC_USERS,
      description: 'Exclusive VIP customer discount',
      descriptionAr: 'خصم حصري لعملاء VIP',
      discountPercentage: 25,
      maxDiscountAmount: 200.00,
      minOrderAmount: 0,
      maxUsesPerUser: 10,
      currentUses: 15,
      validFrom: new Date('2025-01-01T00:00:00Z'),
      validUntil: new Date('2025-12-31T23:59:59Z'),
      applicableUserEmails: ['vip1@example.com', 'vip2@example.com'],
      isFirstBookingOnly: false,
      isPublic: false,
      isFeatured: false,
      campaignName: 'VIP Loyalty Program',
      isActive: true,
      usageCount: 15,
      maxUsagePerUser: 10,
      discountType: 'PERCENTAGE',
      discountValue: 25,
    },
    {
      code: 'REFER100',
      type: PromoCodeType.FIXED_AMOUNT,
      status: PromoCodeStatus.ACTIVE,
      applicability: PromoCodeApplicability.ALL_USERS,
      description: 'Referral bonus for you and your friend',
      descriptionAr: 'مكافأة الإحالة لك ولصديقك',
      discountAmount: 100.00,
      minOrderAmount: 200.00,
      maxUsesPerUser: 1,
      currentUses: 67,
      validFrom: new Date('2025-01-01T00:00:00Z'),
      validUntil: new Date('2025-12-31T23:59:59Z'),
      referrerReward: 50.00,
      refereeReward: 100.00,
      isFirstBookingOnly: true,
      isPublic: true,
      isFeatured: true,
      campaignName: 'Refer a Friend',
      isActive: true,
      usageCount: 67,
      maxUsagePerUser: 1,
      discountType: 'FIXED_AMOUNT',
      discountValue: 100,
    },
    {
      code: 'WEEKEND15',
      type: PromoCodeType.PERCENTAGE,
      status: PromoCodeStatus.ACTIVE,
      applicability: PromoCodeApplicability.ALL_USERS,
      description: 'Weekend special discount',
      descriptionAr: 'خصم عطلة نهاية الأسبوع الخاص',
      discountPercentage: 15,
      maxDiscountAmount: 75.00,
      minOrderAmount: 150.00,
      maxUsesPerUser: 2,
      currentUses: 234,
      validFrom: new Date('2025-01-01T00:00:00Z'),
      validUntil: new Date('2025-12-31T23:59:59Z'),
      applicableDays: [5, 6], // Friday and Saturday
      isFirstBookingOnly: false,
      isPublic: true,
      isFeatured: true,
      campaignName: 'Weekend Special',
      isActive: true,
      usageCount: 234,
      maxUsage: 5000,
      maxUsagePerUser: 2,
      discountType: 'PERCENTAGE',
      discountValue: 15,
    },
    {
      code: 'EXPIRED2024',
      type: PromoCodeType.PERCENTAGE,
      status: PromoCodeStatus.EXPIRED,
      applicability: PromoCodeApplicability.ALL_USERS,
      description: 'New Year 2024 promotion (expired)',
      descriptionAr: 'عرض رأس السنة 2024 (منتهي)',
      discountPercentage: 35,
      maxDiscountAmount: 150.00,
      minOrderAmount: 250.00,
      maxUsesPerUser: 1,
      currentUses: 456,
      validFrom: new Date('2024-12-20T00:00:00Z'),
      validUntil: new Date('2025-01-10T23:59:59Z'),
      isFirstBookingOnly: false,
      isPublic: true,
      isFeatured: false,
      campaignName: 'New Year 2024',
      isActive: false,
      usageCount: 456,
      maxUsage: 1000,
      maxUsagePerUser: 1,
      discountType: 'PERCENTAGE',
      discountValue: 35,
    },
  ];

  for (const promoData of promoCodes) {
    // Check if promo code already exists
    const existing = await promoRepository.findOne({
      where: { code: promoData.code },
    });

    if (!existing) {
      const promo = promoRepository.create(promoData);
      await promoRepository.save(promo);
      console.log(`✅ Created promo code: ${promoData.code}`);
    } else {
      console.log(`ℹ️  Promo code already exists: ${promoData.code}`);
    }
  }

  console.log('✅ Promo codes seeding completed');
}