export enum DisputeCategory {
  PROVIDER_NO_SHOW = 'PROVIDER_NO_SHOW',
  POOR_QUALITY = 'POOR_QUALITY',
  PRICING_DISPUTE = 'PRICING_DISPUTE',
  SAFETY_CONCERN = 'SAFETY_CONCERN',
  UNPROFESSIONAL_BEHAVIOR = 'UNPROFESSIONAL_BEHAVIOR',
  DAMAGE_TO_PROPERTY = 'DAMAGE_TO_PROPERTY',
  INCOMPLETE_SERVICE = 'INCOMPLETE_SERVICE',
  WRONG_SERVICE = 'WRONG_SERVICE',
  LATE_ARRIVAL = 'LATE_ARRIVAL',
  OTHER = 'OTHER',
}

export enum EvidenceType {
  PHOTO = 'PHOTO',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  GPS = 'GPS',
  OTHER = 'OTHER',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PROVIDER_RESPONDED = 'PROVIDER_RESPONDED',
  AWAITING_EVIDENCE = 'AWAITING_EVIDENCE',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum DisputeResolution {
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  NO_REFUND = 'NO_REFUND',
  PROVIDER_WARNING = 'PROVIDER_WARNING',
  PROVIDER_SUSPENSION = 'PROVIDER_SUSPENSION',
  CUSTOMER_WARNING = 'CUSTOMER_WARNING',
  SERVICE_RESCHEDULED = 'SERVICE_RESCHEDULED',
  CREDIT_ISSUED = 'CREDIT_ISSUED',
  CASE_DISMISSED = 'CASE_DISMISSED',
  WITHDRAWN = 'WITHDRAWN'
}

export enum DisputeReportedBy {
  CUSTOMER = 'CUSTOMER',
  PROVIDER = 'PROVIDER',
  SYSTEM = 'SYSTEM',
  ADMIN = 'ADMIN',
}

export enum DisputePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum DisputeEvidenceType {
  PHOTO = 'PHOTO',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  CHAT_HISTORY = 'CHAT_HISTORY',
  VOICE_RECORDING = 'VOICE_RECORDING',
  GPS_LOCATION = 'GPS_LOCATION',
}