export enum PromoCodeType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  FREE_DELIVERY = 'FREE_DELIVERY',
  FIRST_BOOKING = 'FIRST_BOOKING',
}

export enum PromoCodeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SCHEDULED = 'SCHEDULED',
  EXPIRED = 'EXPIRED',
  USED_UP = 'USED_UP',
}

export enum PromoCodeApplicability {
  ALL_USERS = 'ALL_USERS',
  NEW_USERS = 'NEW_USERS',
  SPECIFIC_USERS = 'SPECIFIC_USERS',
  FIRST_BOOKING = 'FIRST_BOOKING',
  SPECIFIC_CATEGORIES = 'SPECIFIC_CATEGORIES'
}

export enum ServiceCategory {
  // Main Categories
  CLEANING = 'CLEANING',
  PLUMBING = 'PLUMBING',
  ELECTRICAL = 'ELECTRICAL',
  CARPENTRY = 'CARPENTRY',
  PAINTING = 'PAINTING',
  AC_MAINTENANCE = 'AC_MAINTENANCE',
  APPLIANCE_REPAIR = 'APPLIANCE_REPAIR',
  PEST_CONTROL = 'PEST_CONTROL',
  MOVING = 'MOVING',
  GARDENING = 'GARDENING',
  CAR_WASH = 'CAR_WASH',
  LAUNDRY = 'LAUNDRY',
  BEAUTY = 'BEAUTY',
  TUTORING = 'TUTORING',
  PET_CARE = 'PET_CARE',
  OTHER = 'OTHER',
}

export enum ServicePricing {
  FIXED = 'FIXED',
  HOURLY = 'HOURLY',
  CUSTOM = 'CUSTOM',
}

export enum ReviewRating {
  ONE_STAR = 1,
  TWO_STARS = 2,
  THREE_STARS = 3,
  FOUR_STARS = 4,
  FIVE_STARS = 5,
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  HIDDEN = 'HIDDEN',
  PUBLISHED = 'PUBLISHED',
}