export enum NotificationType {
  // Booking Related
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  PROVIDER_ASSIGNED = 'PROVIDER_ASSIGNED',
  PROVIDER_EN_ROUTE = 'PROVIDER_EN_ROUTE',
  SERVICE_STARTED = 'SERVICE_STARTED',
  BOOKING_REMINDER = "BOOKING_REMINDER",
  
  // Payment Related
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  
  // Provider Related
  PROVIDER_APPROVED = 'PROVIDER_APPROVED',
  PROVIDER_REJECTED = 'PROVIDER_REJECTED',
  PROVIDER_SUSPENDED = 'PROVIDER_SUSPENDED',
  NEW_BOOKING_REQUEST = 'NEW_BOOKING_REQUEST',
  
  // Review Related
  NEW_REVIEW = 'NEW_REVIEW',
  REVIEW_RESPONSE = 'REVIEW_RESPONSE',
  
  // Dispute Related
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DISPUTE_UPDATED = 'DISPUTE_UPDATED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  
  // Promo & Marketing
  PROMO_CODE_AVAILABLE = 'PROMO_CODE_AVAILABLE',
  SPECIAL_OFFER = 'SPECIAL_OFFER',
  
  // System
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  
  // Chat
  NEW_MESSAGE = 'NEW_MESSAGE',
  
  // General
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  REMINDER = 'REMINDER',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}