export enum PaymentMethod {
  APPLE_PAY = 'APPLE_PAY',
  MADA = 'MADA',
  CREDIT_CARD = 'CREDIT_CARD',
  STC_PAY = 'STC_PAY',
  WALLET = 'WALLET',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export enum PaymentGateway {
  MOYASAR = 'MOYASAR',
  STC_PAY = 'STC_PAY',
  WALLET = 'WALLET',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  PAID = 'PAID'
}

export enum TransactionType {
  BOOKING_PAYMENT = 'BOOKING_PAYMENT',
  WITHDRAWAL = 'WITHDRAWAL',
  CREDIT = 'CREDIT',
  EARNING = 'EARNING',
  DEBIT = 'DEBIT',
  REFUND = 'REFUND',
  WALLET_TOP_UP = 'WALLET_TOP_UP',
  WALLET_WITHDRAWAL = 'WALLET_WITHDRAWAL',
  PROVIDER_REGISTRATION = 'PROVIDER_REGISTRATION',
  PROVIDER_SUBSCRIPTION = 'PROVIDER_SUBSCRIPTION',
  COMMISSION = 'COMMISSION',
  PENALTY = 'PENALTY',
  BONUS = 'BONUS',
}

export enum RefundStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RefundReason {
  PROVIDER_NO_SHOW = 'PROVIDER_NO_SHOW',
  CUSTOMER_CANCELLATION = 'CUSTOMER_CANCELLATION',
  POOR_SERVICE_QUALITY = 'POOR_SERVICE_QUALITY',
  PRICING_DISPUTE = 'PRICING_DISPUTE',
  DUPLICATE_CHARGE = 'DUPLICATE_CHARGE',
  TECHNICAL_ERROR = 'TECHNICAL_ERROR',
  ADMIN_DECISION = 'ADMIN_DECISION',
  OTHER = 'OTHER',
}

export enum Currency {
  SAR = 'SAR',
}