export enum ProviderStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED="APPROVED",
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
  REJECTED = 'REJECTED',
  ON_BREAK = 'ON_BREAK',
}

export enum ProviderVerificationStatus {
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ProviderAvailability {
  AVAILABLE = 'AVAILABLE',
  BUSY = 'BUSY',
  OFFLINE = 'OFFLINE',
}

export enum ProviderDocumentType {
  IQAMA = 'IQAMA',
  NATIONAL_ID = 'NATIONAL_ID',
  COMMERCIAL_REGISTER = 'COMMERCIAL_REGISTER',
  LICENSE = 'LICENSE',
  INSURANCE = 'INSURANCE',
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  BANK_DETAILS = 'BANK_DETAILS',
}

export enum ProviderSubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
}

export enum ProviderRating {
  EXCELLENT = 'EXCELLENT', // 4.5-5.0
  GOOD = 'GOOD', // 4.0-4.49
  AVERAGE = 'AVERAGE', // 3.0-3.99
  POOR = 'POOR', // 2.0-2.99
  VERY_POOR = 'VERY_POOR', // 0-1.99
}

export enum ProviderPenaltyType {
  LATE_CANCELLATION = 'LATE_CANCELLATION',
  NO_SHOW = 'NO_SHOW',
  POOR_SERVICE = 'POOR_SERVICE',
  CUSTOMER_COMPLAINT = 'CUSTOMER_COMPLAINT',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  FRAUDULENT_ACTIVITY = 'FRAUDULENT_ACTIVITY',
}

export enum ProviderBonusType {
  HIGH_RATING = 'HIGH_RATING',
  MONTHLY_TARGET = 'MONTHLY_TARGET',
  CUSTOMER_RETENTION = 'CUSTOMER_RETENTION',
  REFERRAL = 'REFERRAL',
  PEAK_HOURS = 'PEAK_HOURS',
}